[project]
name = "cardiovascular-risk-prediction"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9,<3.10"
dependencies = [
    "matplotlib==3.5.2",
    "numpy==1.23.1",
]

[dependency-groups]
dev = [
    "black==22.6.0",
    "gitpython==3.1.18",
    "pytest==7.1.2",
]
